### PR TITLE
sanders: Remove 'Device is HD Capable' notification when VoLTE is enabled

### PR DESCRIPTION
**Pull request by Keertesh19**
Signed-off-by: Keertesh <keertesh.k98@gmail.com>

### CODE REVIEW

**Comment by Martinusbe** [comment]
added nimmit to review the sign off

**Comment by CheckYourScreen** [comment]
Lol
@keertesh19 is it from payton/potter or you did the changes manually?

**Comment by Keertesh19** [comment]
Lel no @CheckYourScreen its from athene

**Comment by GtrCraft** [comment]
64bitch please

**Comment by Keertesh19** [comment]
It works on 64bitch @GtrCraft

**Pull request merged**
