### PR TITLE
sanders: use patched ims.apk

### PR DESCRIPTION
**Pull request by merothh**
* gets rid of Device is HD Capable Notification
  * pulled from mido

### CODE REVIEW

**Comment by premaca** [comment]
Is this working fine?

**Comment by merothh** [comment]
yes, it is. i tested on PixelExperience by replacing the ims apk.

**Comment by premaca** [comment]
Plz update it for Pie, 9.0 release.

**Comment by merothh** [comment]
sorry, for being late.. I assume it's still to be done ?

**Pull request closed without merging**
